### ISSUE TITLE
feature figure

### ISSUE THREAD

**Issue by duxingyi-charles** [duxingyi-charles/Robust-Implicit-Surface-Networks#1]
![featured](https://user-images.githubusercontent.com/8947527/182003910-f1e39f30-e67b-498b-b990-c2f5964d5020.jpg)

**Comment by qnzhou** [comment]
Upload another version.
![tmp](https://user-images.githubusercontent.com/3606672/187550647-900c8e12-bd57-4270-97da-15a0180e0c39.png)
