### ISSUE TITLE
Run on Mac M1 platform

### ISSUE THREAD

**Issue by cyachen** [duxingyi-charles/Robust-Implicit-Surface-Networks#2]
Would you give some suggestions on configuring with Mac M1. I met the following errors when building.
`
In file included from /Users/chenjiaxi/Desktop/2022/cad/Robust-Implicit-Surface-Networks/build/_deps/indirect_predicates-src/numerics.h:74:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/emmintrin.h:13:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/xmmintrin.h:13:
/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:33:25: error: too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
    ~~~~~~~~~~~~~~~~~~~~^
/Library/Developer/CommandLineTools/usr/lib/clang/13.1.6/include/mmintrin.h:50:19: error: use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
`
And I'm curious about the compiler you use, considering that the Indirect Predicates repo warned that clang on mac is not fully supported.

**Comment by qnzhou** [comment]
I am able to compile the repo on M1.  Here is my compiler info:
```
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: arm64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode_12.4/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

For indirect predicates with clang on mac, we make sure the predicate codes are compiled with `-O0` as instructed by the [README](https://github.com/MarcoAttene/Indirect_Predicates/blob/master/README.md#system-requirements) file (see [here](https://github.com/qnzhou/implicit_predicates/blob/bf24bf4ec152a03365dd7a205e8b8be72aa941d4/cmake/indirect_predicates.cmake#L43-L51)).

**Comment by cyachen** [comment]
Thanks for the info. That's help me a lot.
